"""
app.py
======
MedVisor — AI Medical Education Assistant
Main Gradio application integrating the LLM+RAG backend and the
Diffusion-based image generator into an interactive web UI.

The app combines two generative AI technologies:
  1. LLM + RAG   -> grounded, patient-friendly medical explanations
  2. Diffusion   -> educational medical illustrations

Run:
    python app.py
or in Colab:
    !python app.py   (then open the public Gradio share link)
"""

import os
import gradio as gr
from modules import MedicalRAG, MedicalImageGenerator

# --------------------------------------------------------------------------
# Configuration (override via environment variables)
# --------------------------------------------------------------------------
KB_PATH = os.getenv("KB_PATH", "knowledge_base/medical_facts.json")
IMAGE_MODEL = os.getenv("IMAGE_MODEL", "sdxl-turbo")  # or "sd15"

DISCLAIMER = (
    "⚠️ **Educational use only.** MedVisor generates educational content using AI "
    "and is **not** a substitute for professional medical advice, diagnosis, or "
    "treatment. Always consult a qualified healthcare provider."
)

# --------------------------------------------------------------------------
# Initialize backends once at startup
# --------------------------------------------------------------------------
print("=" * 60)
print("Initializing MedVisor backends...")
print("=" * 60)

rag = MedicalRAG(knowledge_base_path=KB_PATH)
image_gen = MedicalImageGenerator(model_type=IMAGE_MODEL)

print("=" * 60)
print("MedVisor ready!")
print("=" * 60)


# --------------------------------------------------------------------------
# Core pipeline: question -> explanation + illustration
# --------------------------------------------------------------------------
def explain_and_illustrate(question, generate_image, generate_quiz_flag):
    """Main pipeline triggered by the user."""
    if not question or not question.strip():
        return "Please enter a medical question or topic.", None, "", ""

    # ----- 1. LLM + RAG explanation -----
    result = rag.generate_explanation(question, top_k=3)
    explanation = result["explanation"]

    # ----- Sources -----
    sources_md = "### 📚 Retrieved Sources\n"
    for s in result["sources"]:
        sources_md += f"- **{s['topic']}** ({s['category']}) — relevance: {s['score']:.2f}\n"

    # ----- 2. Diffusion illustration -----
    image = None
    if generate_image:
        image = image_gen.generate(result["image_prompt"])

    # ----- 3. Optional quiz -----
    quiz = ""
    if generate_quiz_flag:
        ctx = result["sources"][0]["content"]
        quiz = rag.generate_quiz(result["primary_topic"], ctx)

    full_explanation = f"{explanation}\n\n---\n\n{sources_md}"
    return full_explanation, image, result["image_prompt"], quiz


# --------------------------------------------------------------------------
# Build Gradio UI
# --------------------------------------------------------------------------
def build_ui():
    with gr.Blocks(title="MedVisor — AI Medical Education Assistant",
                   theme=gr.themes.Soft()) as demo:
        gr.Markdown("# 🩺 MedVisor — AI Medical Education Assistant")
        gr.Markdown(
            "Ask about a medical concept. MedVisor uses **LLM + RAG** to generate a "
            "grounded explanation and **Stable Diffusion** to create an educational "
            "illustration."
        )
        gr.Markdown(DISCLAIMER)

        with gr.Row():
            with gr.Column(scale=1):
                question = gr.Textbox(
                    label="Medical Question / Topic",
                    placeholder="e.g., What is an ischemic stroke?",
                    lines=2,
                )
                with gr.Row():
                    gen_image = gr.Checkbox(label="Generate illustration", value=True)
                    gen_quiz = gr.Checkbox(label="Generate quiz question", value=False)
                submit = gr.Button("Explain", variant="primary")

                gr.Examples(
                    examples=[
                        ["What is an ischemic stroke?"],
                        ["Explain the difference between a stroke and a TIA"],
                        ["What causes a heart attack?"],
                        ["How does type 2 diabetes affect the body?"],
                        ["What is Alzheimer disease?"],
                    ],
                    inputs=question,
                )

            with gr.Column(scale=1):
                image_out = gr.Image(label="Educational Illustration", type="pil")
                image_prompt_out = gr.Textbox(
                    label="Image Prompt (generated by LLM)", lines=2
                )

        explanation_out = gr.Markdown(label="Explanation")
        quiz_out = gr.Markdown(label="Quiz")

        submit.click(
            fn=explain_and_illustrate,
            inputs=[question, gen_image, gen_quiz],
            outputs=[explanation_out, image_out, image_prompt_out, quiz_out],
        )
        question.submit(
            fn=explain_and_illustrate,
            inputs=[question, gen_image, gen_quiz],
            outputs=[explanation_out, image_out, image_prompt_out, quiz_out],
        )

    return demo


if __name__ == "__main__":
    demo = build_ui()
    # share=True gives a public link (needed in Colab)
    demo.launch(share=True)
